version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: iris_flask:1.0
    container_name: iris
    ports:
      - 8000:8000
    environment:
      - .env
    volumes:
      - ./model:/app/model